apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: tcp-udp-stream-provider-app
  annotations:
    version: v0.0.1
    description: 'TCP/UDP stream listen provider with test component'
spec:
  components:
    - name: test-component
      type: component
      properties:
        image: file://./component/target/wasm32-wasip2/release/tcp_udp_stream_test_component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: tcp-udp-stream-provider
      type: capability
      properties:
        image: file://./build/tcp-udp-stream-provider.par.gz
        id: tcp-udp-stream-provider
      traits:
        - type: link
          properties:
            target:
              name: test-component
              config:
                - name: stream-config
                  properties:
                    protocol: tcp
                    host: "127.0.0.1"
                    port: "9000"
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
