apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: tcp-udp-stream-demo
  annotations:
    description: 'TCP/UDP Stream Listener Provider Demo'
spec:
  components:
    - name: stream-receiver
      type: component
      properties:
        image: file://./component/build/stream_receiver.wasm
      traits:
        - type: link
          properties:
            target: tcp-udp-provider
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]
            source_config:
              - name: tcp-udp-config
                properties:
                  enable_tcp: 'true'
                  enable_udp: 'true'
                  tcp_port: '8080'
                  udp_port: '8081'

    - name: tcp-udp-provider
      type: capability
      properties:
        image: file://./provider/build/tcp_udp_stream_provider.par.gz
        config:
          - name: default-config
