apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: tcp-udp-stream-example
  annotations:
    description: 'Example application using TCP/UDP stream provider'
    version: v0.1.0
spec:
  components:
    # The TCP/UDP stream provider
    - name: tcp-udp-provider
      type: capability
      properties:
        # NOTE: This should be updated with the actual provider reference
        # once the provider is built and published
        image: file://./target/release/tcp-udp-stream-provider
      traits:
        # Configure which hosts can run this provider
        - type: spreadscaler
          properties:
            instances: 1

    # Example component that receives stream messages
    # NOTE: This is a placeholder - you need to create an actual component
    - name: stream-consumer
      type: component
      properties:
        # Replace with your actual component reference
        image: file://./path/to/your/component.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        # Link the component to the TCP/UDP provider
        - type: link
          properties:
            target: tcp-udp-provider
            namespace: wasmcloud
            package: stream
            interfaces: [messages]
            target_config:
              - name: tcp-connection
                properties:
                  tcp:
                    - host: localhost
                      port: 8080
                      reconnect_delay_ms: 5000
